MusicBrowser/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MusicBrowser.Models
{
    public class Artist
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImgSource { get; set; }
        public int Listeners { get; set; }
        public bool isFav { get; set; }



    }
}

MusicBrowser/Models/Weather.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Script.Serialization;

namespace MusicBrowser.Models
{
    public class Weather
    {
        public string city;
        public Weather(string city)
        {
            this.city = city;
        }
        
        public Object getWeatherForecast()
        {
          
            string appid = "adf871fab3963fca2fa822af432e5c89";
            string url = "http://api.openweathermap.org/data/2.5/weather?q=" + city + "&APPID=" + appid + "&units=imperial";
            //synchronous client.
            var client = new WebClient(); //it makes possible to take response as a string
            var content = client.DownloadString(url);
            var serializer = new JavaScriptSerializer(); //it makes possible to change string to json object
            var jsonContent = serializer.Deserialize<Object>(content);
            return jsonContent;

        }





    }
}

MusicBrowser/Controllers/ArtistController.cs
using MusicBrowser.DAL;
using MusicBrowser.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicBrowser.Controllers
{
    public class ArtistController : Controller
    {
        private ArtistsContext db = new ArtistsContext();
        public ActionResult YourArtists()
        {
            return View(db.Artists);
        }

        [ChildActionOnly]
        public ActionResult ArtistList(int choice)
        {

            List<Artist> artists;

            switch(choice)
            {

                case 1: artists = db.Artists.OrderBy(a => a.Name).ToList(); break;
                case 2: artists = db.Artists.OrderByDescending(a => a.Name).ToList(); ; break;
                case 3: artists = db.Artists.OrderByDescending(a => a.Listeners).ToList(); break;




                default: artists = null; break;
            }

            return PartialView("_ArtistList", artists);
        }

        public ActionResult SearchArtist()
        {
            return View();
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

MusicBrowser/Controllers/WeatherController.cs
using MusicBrowser.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicBrowser.Controllers
{
    public class WeatherController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ParisWeather()
        {
            return View();
        }

        public JsonResult GetWeather(string city)
        {
            Weather weath = new Weather(city);

            return Json(weath.getWeatherForecast(), JsonRequestBehavior.AllowGet );  // HTTP GET requests from the client are allowed.

        }

        public ActionResult WeatherSearcher()
        {
            return View();
        }




    }
}

MusicBrowser/Views/Artist/Index.cshtml
<h1> MUSIC</h1>
<a class="a" href="@Url.Action("YourArtists", "Artist")">Your favourite artists</a>
<a class="a" href="@Url.Action("SearchArtist", "Artist")">Search artist</a>



<style>
    .a {
        font-size: 30px;
        border: double;
        margin-bottom: 30px;
        margin-top: 30px;
        width: 300px;
        float: left; /* add this */
        margin-left: 30px;
        position: center;
        text-align: center;
    }
</style>

MusicBrowser/Views/Artist/SearchArtist.cshtml
<br />
<br />
<input type="text" id="artistForm" />
<button id="search-artist">Search artist</button>
<div id="smth"></div>

<button id="previous">previous</button>
<button id="next">next</button>

<script>
    var pageNumber;

    $(document).ready(function () {
        $("#search-artist").click(function () {
            pageNumber = 1;
            listLogic(pageNumber)
        })
    });


    $(document).ready(function () {
        $("#next").click(function () {
            pageNumber++;
            listLogic(pageNumber)
            console.log(pageNumber);
        }
        )
    }
    )


    $(document).ready(function () {
        $("#previous").click(function () {
            pageNumber--;
            listLogic(pageNumber);
            console.log(pageNumber);
        }
        )
    }
    )


    function listLogic(pageNumber) {
        var artistName = searchAritst();
        $("#smth").html("");
        $.get("http://ws.audioscrobbler.com/2.0/?method=artist.search&artist=" + artistName + " &api_key=fa1b419ee7f2e7b9799a173bb7cb6ea4&format=json&limit=10&page=" + pageNumber, function (response) {
            var html = '';
            var artists = response.results.artistmatches.artist;
            var x = "ssssssssssss"
            for (i = 0; i <= 9; i++) {
                html += "<div onclick=getInfo(this) id= artist" + i + ">" + artists[i].name + "</div>";
            }
            document.getElementById("smth").innerHTML += html;


        });
    }


    function searchAritst() {
        return document.getElementById("artistForm").value
    }


    function getInfo(id) {
        var a = this.innerHTML
        console.log(id.innerHTML)
    }

    function setMyValue(value) {
        $('#myVar').val("obiekt");
    }

</script>

MusicBrowser/Views/Artist/YourArtists.cshtml
@{

    int sorting = 1;
    int helper;
    bool result = int.TryParse((Request["HowSorted"]), out helper);

    if (result == true)
    {
        sorting = helper;
    }

}
<h1>Your favourite artists</h1><br />


@Html.Action("ArtistList", new { choice = sorting })
<div>
    <form action="" method="post">
        <p>
            <br />
            <label for="text1">Sort By</label><br>
            <input type="radio" name="HowSorted" value=1>A-Z<br>
            <input type="radio" name="HowSorted" value=2>Z-A<br>
            <input type="radio" name="HowSorted" value=3>Most listened<br><br>
            <input id="HowSortedInput" type="submit" value="Ok">
        </p>

    </form>


</div>



<script>
    $(document).ready(function () {
        $("#inpp").click(function () {
            $.get("@Html.Action("ArtistList", new { choice = 3} )", function (response) {
                //response
                $("#name").text(response.name);
                $("#temp").text(response.main.temp);
                $("#humidity").text(response.main.humidity);

            });
        });
    });
</script>

MusicBrowser/Views/Artist/_ArtistList.cshtml
@foreach (var artist in Model)
    {
        <li>@artist.Name ( @artist.Listeners listeners on LAST.FM )</li>
    }

MusicBrowser/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Weather", "Index", "Weather", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("MUSIC", "Index", "Artist", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="position:absolute; top:700px">
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>


</body>
</html>

MusicBrowser/Views/Weather/Index.cshtml
<h1> WEATHER</h1>
<a class="a" href="@Url.Action("ParisWeather", "Weather")">Check weather conditions in Paris</a>
<a class="a" href="@Url.Action("WeatherSearcher", "Weather")">Search for weather in your city</a>



<style>
    .a {
        font-size: 30px;
        border: double;
        margin-bottom: 30px;
        margin-top: 30px;
        width: 300px;
        float: left; /* add this */
        margin-left: 30px;
        position: center;
        text-align: center;
    }
</style>

MusicBrowser/Views/Weather/ParisWeather.cshtml
<h2>Weather in Paris right now</h2>

<p id="name"></p>
<p id="temp"></p>
<p id="humidity"></p>

<button>Get Weather</button>
<script>
    //Whenever you use jQuery to manipulate your web page,
    //you wait until the document ready event has fired.
    //The document ready event signals that the DOM of the page
    //is now ready, so you can manipulate it without worrying
    //that parts of the DOM has not yet been created.
    //The document ready event fires before all images
    //etc.are loaded, but after the whole DOM itself is ready
    $(document).ready(function () {
        $("button").click(function () {
            $.get("@Url.Action("GetWeather","Weather" , new { city = "Paris" } )", function (response) {
                //response
                $("#name").text("city: " + response.name);
                $("#temp").text("temperature: " + response.main.temp + "F");
                $("#humidity").text("humidity: " + response.main.humidity + "%");
            });
        });
    });
</script>

MusicBrowser/Views/Weather/WeatherSearcher.cshtml
<br />
<input type="text" id="city" />

<br />
<br />

<p id="name"></p>
<p id="temp"></p>
<p id="humidity"></p>


<button>Search weather</button>


<script>
    $(document).ready(function () {
        $("button").click(function () {
            var city = search();
            $.get("http://api.openweathermap.org/data/2.5/weather?q=" + city + "&APPID=adf871fab3963fca2fa822af432e5c89&units=imperial", function (response) {
                $("#name").text("city: " + response.name);
                $("#temp").text("temperature: " + response.main.temp + "F");
                $("#humidity").text("humidity: " + response.main.humidity +"%");

            });
        });
    });


    function search() {
        return document.getElementById("city").value
    }

</script>